### ISSUE TITLE
Add a readme file to showcase the use of resources

### ISSUE THREAD

**Issue by pradyumnjain** [DeepConnectAI/Self_Paced_Learning#1]

**Comment by tarunjain1st** [comment]
can i take this

**Comment by pradyumnjain** [comment]
hey @tarunjain1st  go throght the structure of repo and resources and device a README.md file that can best help the users to navigate through the material.

**Comment by pradyumnjain** [comment]
Hey, @tarunjain1st go through the structure of repo and resources and device a README.md file that can best help the users to navigate through the material.

**Comment by tarunjain1st** [comment]
okay sure @pradyumnjain

**Comment by tarunjain1st** [comment]
do you want me to work on the main README.md file else should i create separate to avoid multiple commit a once.

**Comment by pradyumnjain** [comment]
@tarunjain1st you can work on the main README.md, by making it more engaging and generalized.

**Comment by tarunjain1st** [comment]
okay

**Comment by tarunjain1st** [comment]
did you want to keep data of previous readme.md, or should i replace all

**Comment by tarunjain1st** [comment]
hey @pradyumnjain kindly check my PR its has come conflicts, can you please look into it.

**Comment by pradyumnjain** [comment]
Sure @tarunjain1st  will go through it

**Comment by pradyumnjain** [comment]
Hey, @tarunjain1st great work, just a few pointers change the content and for python and machine learning, go towards a more practical explanation. If possible also do mention a detailed learning path for beginners in the field of machine learning as creatively as you can. Also for your convenience, I have created a branch by your name, so make a PR on that it will be merged to master later.

**Comment by pradyumnjain** [comment]
Also, next time you make a PR link, it with the issue (update not close with merge).

**Comment by tarunjain1st** [comment]
what else do i need to add in this apart from detailed learning path?

**Comment by tarunjain1st** [comment]
can you give a brief info about how you want your readme

**Comment by pradyumnjain** [comment]
Alright here are few specific changes
1) write why python is so powerful and used so commonly for data-driven tasks
2) write use cases for AI in our everyday life depicting its importance
3) Come up with a detailed learning path for beginners in the field
The rest was Perfect No changes required.

**Comment by tarunjain1st** [comment]
Hey @pradyumnjain kindly merge the PR i have done with the Updates

**Comment by pradyumnjain** [comment]
Thank you so much contributing @tarunjain1st  your PR was merged, hope you got to learn something along the way as well. :)
