### ISSUE TITLE
NLP_BASICS

### ISSUE THREAD

**Issue by kanikamittal1811** [DeepConnectAI/Self_Paced_Learning#8]

**Comment by kishanpython** [comment]
I want to work on it. Can you assign this to me?

**Comment by pradyumnjain** [comment]
@kishanpython You can start by creating resources mentioned in the above guidance. They are not to be strictly followed though. Make resources using code snippets that best explain the important concepts related to the given topic.

**Comment by pradyumnjain** [comment]
@kishanpython after a review your PR was successfully merged. Congratulations. Hope you got to learn new things along the way as well.
